application: stresschill
version: test
runtime: python
api_version: 1

handlers:
-   url: /download
    static_dir: static/download
-   url: /images
    static_dir: static/images
-   url: /css
    static_dir: static/css
-   url: /favicon.ico
    static_files: static/images/favicon.ico
    upload: static/images/favicon.ico
-   url: /remote_api
    script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
    login: admin
-   url: /task/.*
    script: process.py
    login: admin
-   url: /debug/.*
    script: debug.py
    login: admin
-   url: /.*
    script: main.py
